import { defineConfig } from 'astro/config';
import { storyblok } from '@storyblok/astro';
import node from '@astrojs/node';
import mkcert from 'vite-plugin-mkcert';
import { loadEnv } from 'vite';

const env = loadEnv(process.env.NODE_ENV, process.cwd(), '');

/**
 * tokens/dist/tokens.css is generated by `npm run build:tokens` and imported by
 * BaseLayout. It sits outside src/, so Vite doesn't invalidate the module graph
 * when Style Dictionary rewrites it — a rebuilt token would only show up after
 * an unrelated src/ edit or a dev-server restart. Watch it and force a reload
 * so a Figma token change is visible immediately.
 */
const watchTokens = {
  name: 'primer:watch-tokens',
  configureServer(server) {
    const tokensCss = new URL('./tokens/dist/tokens.css', import.meta.url).pathname;
    server.watcher.add(tokensCss);
    server.watcher.on('change', (file) => {
      if (file !== tokensCss) return;
      server.moduleGraph.invalidateAll();
      server.ws.send({ type: 'full-reload' });
    });
  },
};

export default defineConfig({
  output: 'server',
  adapter: node({ mode: 'standalone' }),
  integrations: [
    storyblok({
      accessToken: env.STORYBLOK_TOKEN,
      livePreview: true,
      components: {
        page:          'storyblok/Page',
        resource:      'storyblok/Page',
        campaign_page: 'storyblok/Page',
        hero:          'storyblok/Hero',
        feature_grid:  'storyblok/FeatureGrid',
        cta_banner:    'storyblok/CTABanner',
        logo_bar:      'storyblok/LogoBar',
        gallery:       'storyblok/Gallery',
        testimonials:  'storyblok/TestimonialBlock',
        two_column:    'storyblok/TwoColumn',
        rich_text:     'storyblok/RichText',
        stats_bar:     'storyblok/StatsBar',
        card_grid:     'storyblok/CardGrid',
        button:        'storyblok/Button',
        header:        'storyblok/Header',
        footer:        'storyblok/Footer',
        team:          'storyblok/Team',
        tabs:          'storyblok/Tabs',
        faq:           'storyblok/FAQ',
        pricing_table: 'storyblok/PricingTable',
        contact_form:  'storyblok/ContactForm',
        process_steps: 'storyblok/ProcessSteps',
        video:         'storyblok/Video',
        resource_header:   'storyblok/ResourceHeader',
        case_study_layout: 'storyblok/CaseStudyLayout',
        key_takeaway_item: 'storyblok/KeyTakeawayItem',
        sidebar_cta:       'storyblok/SidebarCTA',
        testimonial:       'storyblok/Testimonial',
      },
      apiOptions: { region: 'eu' },
    }),
  ],
  vite: { plugins: [mkcert(), watchTokens] },
});
